<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="diff_drive_controller" params="wheel_separation wheel_radius wheel_torque">
    <gazebo>
      <plugin
        filename="gz-sim-diff-drive-system"
        name="gz::sim::systems::DiffDrive">
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_radius>${wheel_radius * 2}</wheel_radius>

        <max_linear_acceleration>1</max_linear_acceleration>
        <min_linear_acceleration>-1</min_linear_acceleration>
        <max_angular_acceleration>2</max_angular_acceleration>
        <min_angular_acceleration>-2</min_angular_acceleration>
        <max_linear_velocity>0.5</max_linear_velocity>
        <min_linear_velocity>-0.5</min_linear_velocity>
        <max_angular_velocity>1</max_angular_velocity>
        <min_angular_velocity>-1</min_angular_velocity>

        <topic>cmd_vel</topic>
        <odom_topic>odom</odom_topic>
        <odom_publish_frequency>20</odom_publish_frequency>

        <frame_id>odom</frame_id>
        <child_frame_id>base_footprint</child_frame_id>
      </plugin>

      <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
        <joint_name>left_wheel_joint</joint_name>
        <joint_name>front_right_wheel_joint</joint_name>
        <topic>/joint_states</topic>
      </plugin>

    </gazebo>
  </xacro:macro>
</robot>
