# This file contains deltas to be applied to the base navigation
# config file for GPS mode.

global_costmap:
  global_costmap:
    ros__parameters:
      rolling_window: true
      width: 50
      height: 50
      track_unknown_space: false
      # Removed "static_layer" for gps mode
      plugins: ["obstacle_layer", "voxel3d_layer", "inflation_layer"]
