# This file contains deltas to be applied to the base navigation
# config file for using the custom fixed-path planner with 
# the stock RegulatedPurePursuitController controller.

controller_server:
  ros__parameters:
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 2.0 #1.0
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 0.5
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: false
      allow_reversing: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 3.2
      max_robot_pose_search_dist: 10.0
      use_interpolation: false
      
planner_server:
  ros__parameters:
    GridBased:
      plugin: "nav2_fixed_path_planner/FixedPath"
      interpolation_resolution: 0.1
      waypoints: "[[0.0, 0.0], [0.04, 2.79], [-0.16, 4.36], [0.38, 5.44], [3.0, 5.7], [3.9, 4.1], [2.9, 1.3], [2.9, -0.87], [3.2, -3.7], [3.7, -5.8], [3.2, -6.8], [2.2, -7.5], [1.13, -7.6], [0.09, -7.0], [0.05, -5.0], [0.5, -2.1]]"

