<?xml version="1.0"?>
<robot name="elsabot_4wd" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find elsabot_4wd)/urdf/4wd_properties.urdf.xacro" />
  <xacro:include filename="$(find elsabot_4wd)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find elsabot_4wd)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find elsabot_4wd)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find elsabot_4wd)/urdf/sensors/gps.urdf.xacro" />
  <xacro:include filename="$(find elsabot_4wd)/urdf/sensors/generic_laser.urdf.xacro" />
  <!--xacro:include filename="$(find elsabot_4wd)/urdf/sensors/depth_sensor.urdf.xacro" /-->
  <xacro:include filename="$(find elsabot_4wd)/urdf/sensors/oakd_on_ptbase.urdf.xacro" />
  <xacro:include filename="$(find elsabot_4wd)/urdf/controllers/skid_steer.urdf.xacro" />

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />
  <xacro:wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:imu/>
  <xacro:gps/>
  
  <xacro:generic_laser>
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>
  
  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

 <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />

  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-magnetometer-system" name="gz::sim::systems::Magnetometer"/>
    <plugin filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>
  </gazebo>

 </robot>
